version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on: []
    

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_USER_URL=http://localhost:3000/api/users

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: sunenglish
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prepv3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
